NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="ARBT"
ORG_URL="https://acoshirabbit.com"
ORG_LOGO="https://acoshirabbit.com/logo2.png"
ORG_DESCRIPTION="Acoshi Rabbit (ARBT) is a revolutionary meme-inspired cryptocurrency for the masses, $arbt has learnt a few tricks from the memes father Dogecoin and aims to sustain a more profitable cryptoverse for beginners and enthusiasts. ARBT tokens will last in existence for as long as Stellar blockchain network exist, if you are a small player in some of the most popular memecoins on the Stellar network you may be eligible to get free ARBT tokens through airdrop in your pending payments."
ORG_PHYSICAL_ADDRESS="Milan, Italy"
ORG_KEYBASE="acoshirabbit"
ORG_TWITTER="AcoshiRabbit"
ORG_OFFICIAL_EMAIL="info@acoshirabbit.com"

[[CURRENCIES]]
code="ARBT"
issuer="GBJUUYLCALIBUOLEWDJKAWCWVWQ7AV3T2FBFVVNB3KRJIZ3U2RFSCDLR"
display_decimals=7
name="Acoshi Rabbit"
desc="Acoshi Rabbit (ARBT) is a revolutionary meme-inspired cryptocurrency for the masses, $arbt has learnt a few tricks from the memes father Dogecoin and with Stellar's reliable and efficient infrastructure $arbt aims to sustain a more profitable cryptoverse for beginners and enthusiasts. If you are a small player in some of the most popular memecoins on the Stellar network you may be eligible to get free ARBT tokens through airdrop in your pending payments."
is_asset_anchored=false
conditions="There will only ever be 100,000,000,000 ARBT tokens in existence and will last for as long as Stellar blockchain network exist."
image="https://acoshirabbit.com/logo.png"
fixed_number=100000000000
status="live"
